# Generated by Django 6.0.2 on 2026-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_add_notice_messaging_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlist',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketlist',
            name='status',
            field=models.CharField(choices=[('pending', 'পেন্ডিং'), ('approved', 'লিস্ট অনুযায়ী কেনা হচ্ছে'), ('delivered', 'পৌঁছানো'), ('declined', 'প্রত্যাখ্যান')], default='pending', max_length=30),
        ),
    ]
