# Generated by Django 6.0.2 on 2026-02-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_pack_id_and_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlist',
            name='ai_content',
            field=models.TextField(blank=True),
        ),
    ]
