# Generated by Django 6.0.2 on 2026-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_add_ai_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='area_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='building_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='floor_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='room_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='section_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
