# Generated by Django 6.0.2 on 2026-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_add_delivery_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
