# Generated by Django 6.0.2 on 2026-02-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_add_profile_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketlist',
            name='list_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, unique=True),
        ),
    ]
