# Generated by Django 6.0.2 on 2026-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_pack_id_unique_by_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/avatars/'),
        ),
    ]
