# Generated by Django 6.0.2 on 2026-02-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_add_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
    ]
