# Generated by Django 6.0.2 on 2026-02-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_add_extra_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('section_no', models.CharField(blank=True, max_length=50)),
                ('building_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['area_name', 'section_no', 'building_name'],
                'unique_together': {('area_name', 'section_no', 'building_name')},
            },
        ),
        migrations.CreateModel(
            name='PathwayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pathway_images/%Y/%m/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.pathway')),
            ],
            options={
                'ordering': ['pathway', 'position'],
            },
        ),
    ]
