# Generated by Django 6.0.2 on 2026-02-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_add_pathway'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathwayimage',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
