# Generated by Django 6.0.2 on 2026-02-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_deliveryflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendStatusPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='marketlist',
            name='status',
            field=models.CharField(choices=[('pending', 'পেন্ডিং'), ('approved', 'প্রসেসিং...'), ('delivered', 'Delivered'), ('declined', 'প্রত্যাখ্যান')], default='pending', max_length=30),
        ),
    ]
