# Generated by Django 6.0.2 on 2026-02-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_sendstatuspreset_alter_marketlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryflow',
            name='status_text',
            field=models.CharField(blank=True, default='Approved', max_length=255),
        ),
        migrations.AlterField(
            model_name='marketlist',
            name='status',
            field=models.CharField(choices=[('pending', 'পেন্ডিং'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('declined', 'প্রত্যাখ্যান')], default='pending', max_length=30),
        ),
    ]
