# Generated by Django 6.0.2 on 2026-02-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_deliveryflow_status_text_alter_marketlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryflow',
            name='status_text',
        ),
    ]
