# Generated by Django 6.0.2 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_deliveryflow_status_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryflow',
            name='status_text',
            field=models.CharField(blank=True, default='Approved', max_length=255),
        ),
    ]
